### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by pherum** [jack-theripper/yandex-disk-flysystem#1]
добавьте пожалуйста tag версий для composer. там тоже https://github.com/jack-theripper/yandex
изменение minimum-stability вытягивает dev пакеты(

**Comment by jack-theripper** [comment]
@PheRum 
Здравствуйте. Честно сказать, я Вас не очень понимаю, что означает "tag версий" ? Поясните пожалуйста.
У вас не получается установить зависимости из-за "minimum-stability" или дело только в dev-зависимостях ?

**Comment by pherum** [comment]
@jack-theripper метки проставmте на стабильные состояния)
dev-master git выкачивает в то время как наличие метки выкачивает архивный пакет, что в разы быстрее + локальный кеш в композере.

если же добавить в require только этот пакет, который имеет зависимость arhitector/yandex, то выдаст ошибку.....

метки проставьте, пожалуйста))
в обоих пакетах

**Comment by jack-theripper** [comment]
:+1:
