### ISSUE TITLE
Conflict with the latest league/flysystem

### ISSUE THREAD

**Issue by pavel-macovschi** [jack-theripper/yandex-disk-flysystem#7]
Please update dependencies to the latest version of league/flysystem. 

Now I have this type of conflict: 

`Problem 1
    - Root composer.json requires arhitector/yandex-disk-flysystem dev-master -> satisfiable by arhitector/yandex-disk-flysystem[dev-master].
    - arhitector/yandex-disk-flysystem dev-master requires league/flysystem ^1.0 -> found league/flysystem[1.0.0, ..., 1.1.10] but it conflicts with your root composer.json require (^3.15).
`

**Comment by pavel-mk** [comment]
I've checked a few methods in a class. There is no backward compatibility between Yandex SDK. So to make this adapter compatible with a new version need to rewrite methods and make it fully compatible  with the Flysystem Adapter Interface.
